### PR TITLE
Remove version escaping in sentry_upload_sourcemaps

### LINKED ISSUE #57: Version parameter escaped in sentry_upload_sourcemap but not in sentry_upload_file
I have some ad-hoc code on our CI to manually create Sentry releases using Fastlane.

It's a React Native application, so the code takes care of uploading the bundle file, as well as the sourcemaps.

Interestingly, I've found out that [`upload_file`](https://github.com/getsentry/sentry-fastlane-plugin/blob/master/lib/fastlane/plugin/sentry/actions/sentry_upload_file.rb#L19) treats the version string as it is passed, but [`upload_sourcemap`](https://github.com/getsentry/sentry-fastlane-plugin/blob/master/lib/fastlane/plugin/sentry/actions/sentry_upload_sourcemap.rb#L19) escapes the string provided, so it feels there is some inconsistency there. Is the escaping needed? Could it be removed?

My `version` name contains special characters like `+`, so I can't match the `version` because when executing `upload_sourcemaps`, the escaping will prepend a backlash on every special characters, for example with the 'plus' character: ` + => \+ `. 

It would be great to remove the escaping if it doesn't arise any security concerns.

### PR DESCRIPTION
**Pull request by dantereve**
To harmonize with other actions, I propose to delete the version's escaping for `sentry_upload_sourcemaps`, which is causing some issues with the version number. 
This PR will resolve #57.

### CODE REVIEW

**Comment by dannysking91** [comment]
I'm also running into the issue described in https://github.com/getsentry/sentry-fastlane-plugin/issues/57.



@HazAT @dantereve what would it take to get this change merged and released?

**Comment by maxammann** [comment]
Running into the same problem. Would love to see this fixed :)

**Review by philipphofmann — APPROVED** [review]
LGTM, Thanks 👏

**Comment by maxammann** [comment]
Looking forward to the next release!

**Pull request merged**
