### PR TITLE
fix: Set `--finalize` CLI parameter when `finalize` option is set to `true`

### PR DESCRIPTION
**Pull request by bricker**
This is a **BREAKING** change. Releases which were not previously being finalized when `finalize:true` was passed will now be finalized.

Previously, the `--finalize` flag was only being added if `params[:finalize]` was `nil`. Setting `finalize: true` would not finalize the release.

This PR fixes the code to match the documentation and expected behavior.

### CODE REVIEW

**Comment by lukeredpath** [comment]
@bricker why was this issue closed? The current behaviour is wrong and does not match the documentation.

**Comment by bricker** [comment]
> @bricker why was this issue closed? The current behaviour is wrong and does not match the documentation.

There didn't seem to be any interest from the Sentry team in merging this fix. Regardless, you're right, it's still an issue and I'll re-open this PR. I am not currently using this plugin on any projects, so someone else may be in a better position to shepherd this fix into a release.

**Comment by lukeredpath** [comment]
@HazAT can this issue be revisited please? It seems a bit odd that this currently does the opposite of what it should be doing.

**Comment by philipphofmann** [comment]
Thanks for doing this, @bricker. I think this is not a breaking change as with the old way of handling the finalize parameter; only the test `adds --finalize if set to true` fails, and this is fixed with your new behavior. If you include a line in the changelog, we can ship this as a regular fix.

**Comment by bricker** [comment]
@philipphofmann done, thanks!

**Review by philipphofmann — APPROVED** [review]
LGTM 🚀

**Pull request merged**
