### PR TITLE
Added sentry cli path as parameter for actions.

### PR DESCRIPTION
**Pull request by tomzr**
Added sentry cli path as parameter for actions.

Solves #34

### CODE REVIEW

**Comment by HazAT** [comment]
Thanks for the PR, I think it makes sense. 
It seems it needs some work to fix all the tests (how we install sentry-cli).
When I find time for this I will merge/fix it.

**Comment by dalu93** [comment]
Hi @HazAT, any plans to fix and merge this PR? It would be very beneficial for me

**Comment by keima** [comment]
@HazAT Any updates?

**Comment by HazAT** [comment]
@philipphofmann Can you check this please?

**Comment by chrisgibbs** [comment]
This feature is crucial to supporting Sentry CLI on CI machines. With it, the path can reference a CLI binary included in the project source, rather than what is installed on the CI machine. Without it companies that rely on other teams for CI machine management have to wait for every new version of the CLI to be installed before it can be used.

Can we expedite the review and merge of this feature?

**Review by philipphofmann — COMMENTED** [review]
Thanks a lot for this PR @tomzr, and sorry for reaching out to you after more than two years. Can you please add `sentry_cli_path` as well to upload_proguard and set_commits. Please as well fix the tests and add some tests to validate the functionality. Apart from that, the PR already looks pretty good.

**Comment by tomzr** [comment]
sorry, im quite new in ruby so i dont know much whats happening there, but as i understand there is some versioning issue which i somewhat hacked in order to force bundler updating package.. anyway i quite dont understand that requirement and as we dont use sentry anymore i'll let that up to you

**Comment by draperunner** [comment]
This option would be useful to us also. Hoping it will get merged and released.

We use the following hack for now to get around this issue. Our `node_modules/.bin` is temporarily added to `PATH` before `sentry_upload_dsym` runs.

```diff
 download_dsyms(
   version: "latest"
 )
+ENV["PATH"] = "../node_modules/.bin:#{ENV['PATH']}"
 sentry_upload_dsym(
    org_slug: '<our org>',
    project_slug: '<our app>',
 )

**Comment by bruno-garcia** [comment]
Does it make sense to merge this and add what's missing on a second PR?

**Comment by philipphofmann** [comment]
We can close this as we have https://github.com/getsentry/sentry-fastlane-plugin/pull/97.

**Pull request closed without merging**
